language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

cache:
  directories:
    - vendor

install:
  - travis_retry composer install --no-interaction --no-dev --ignore-platform-reqs

script:
  - vendor/bin/phpunit --verbose

matrix:
  fast_finish: true
